// resources/admin/elementor/SearchableSelect.vue
<script setup>
import {ref, onMounted} from 'vue';
import {useDebounce} from "@/mixin/useDebounce";
import Rest from "@/utils/http/Rest";
import translate from "@/utils/translator/Translator";

const props = defineProps({
  value: {
    type: [String, Number],
    default: ''
  },
  onChange: {
    type: Function,
    required: true
  }
});

const searchTerm = ref('');
const options = ref({});
const loading = ref(false);

const searchProducts = async (search, includeIds) => {
  loading.value = true;
  try {
    const queryParams = {
      "active_view": 'publish',
      "per_page": 10,
      "page": 1,
      "search": search,
      'filter_type': 'simple',
      'sort_by': 'ID',
      'with': ['detail', 'variants']
    };

    if (includeIds) {
      queryParams['include_ids'] = [includeIds];
    }
    Rest.get('products', queryParams)
        .then(response => {
          const newOptions = {};
          response.products.data.forEach(product => {
            newOptions[product.ID.toString()] = {
              value: product.ID.toString(),
              label: product.post_title,
              product: product
            };
          });

          options.value = newOptions;

        })
        .catch((errors) => {
          console.log(errors);
        })
        .finally(() => {

        });

  } catch (error) {
    console.error('Error loading products:', error);
  } finally {
    loading.value = false;
  }
};

const debouncedSearch = useDebounce(() => {
  searchProducts(searchTerm.value);
}, 500);

const handleSearchChange = (newSearch) => {
  searchTerm.value = newSearch;
  debouncedSearch();
};

const handleOptionClick = (option) => {
  props.onChange(option);
};

onMounted(() => {
  searchProducts('', props.value);
});
</script>

<template>
  <div>
    <div class="searchable-select-container">
      <el-select
          v-model="searchTerm"
          filterable
          remote
          :placeholder="translate('Search for products...')"
          :remote-method="handleSearchChange"
          :loading="loading"
          @change="(value) => {
            const option = Object.values(options).find(opt => opt.label === value);
            if (option) handleOptionClick(option);
          }"
      >
        <el-option
            v-for="option in Object.values(options)"
            :key="option.value"
            :label="option.label"
            :value="option.label"
            :class="{ 'option-item-selected': value === option.value }"
        />
        <template #empty>
          <div v-if="loading" class="searchable-select-loading">{{ translate('Loading...') }}</div>
          <div v-else-if="searchTerm" class="no-results">{{ translate('No products found.') }}</div>
        </template>
      </el-select>
    </div>
  </div>
</template>

<style scoped>

</style>

// resources/admin/BlockEditor/Components/SearchableSelect.jsx
import {useDebounce} from "@/mixin/useDebounce";
import blocktranslate from "@/BlockEditor/BlockEditorTranslator";

const {useState} = wp.element;
const {TextControl} = wp.components;
const {apiFetch} = wp;
const {addQueryArgs} = wp.url;
const rest = window['fluentCartRestVars'].rest;

const styles = {
    container: {
        position: 'relative',
    },
    optionsList: {
        margin: '0',
        padding: '0',
        listStyle: 'none',
        border: '1px solid #ccc',
        borderRadius: '4px',
        maxHeight: '200px',
        overflowY: 'auto',
    },
    optionItem: {
        padding: '8px 12px',
        cursor: 'pointer',
        transition: 'background-color 0.2s',
        backgroundColor: '#fff',
    },
    optionItemHover: {
        backgroundColor: '#f0f0f0',
    },
    optionItemSelected: {
        backgroundColor: '#e0e0e0',
    },
    noResults: {
        padding: '8px 12px',
        color: '#666',
        fontStyle: 'italic',
    },
    loading: {
        padding: '8px 12px',
        color: '#666',
        textAlign: 'center',
    }
};

const SearchableSelect = ({value, onChange}) => {
    const [searchTerm, setSearchTerm] = useState('');
    const [options, setOptions] = useState({});
    const [hoveredIndex, setHoveredIndex] = useState(null);
    const [loading, setLoading] = useState(false);
    const searchProducts = async (search, includeIds) => {

        setLoading(true);
        try {
            const queryParams = {
                "active_view": 'publish',
                "per_page": 10,
                "page": 1,
                "search": search,
                'filter_type': 'simple',
                'sort_by': 'ID',
                'with': ['detail', 'variants']
            };

            if (includeIds) {
                queryParams['include_ids'] = [includeIds];
            }

            const response = await apiFetch({
                path: addQueryArgs('fluent-cart/v2/products', queryParams),
                headers: {
                    'X-WP-Nonce': rest.nonce
                }
            });

            const newOptions = response.products.data.reduce((acc, product) => {
                acc[product.ID.toString()] = {
                    value: product.ID.toString(),
                    label: product.post_title,
                    product: product
                };
                return acc;
            }, {});

            setOptions(newOptions);

        } catch (error) {
            console.error('Error loading products:', error);
        } finally {
            setLoading(false);
        }
    };
    const debouncedSearch = useDebounce((term) => {
        searchProducts(searchTerm)
    }, 500);



    const {useEffect} = wp.element;

    useEffect(() => {
        searchProducts('', value);
    }, []);

    return (
        <div>
            <div style={styles.container}>
                <TextControl
                    placeholder={blocktranslate("Search products...")}
                    value={searchTerm}
                    onChange={(newSearch) => {
                        setSearchTerm(newSearch);
                        debouncedSearch(newSearch);
                    }}
                />
                {loading ? (
                    <div style={styles.loading}>{blocktranslate("Loading...")}</div>
                ) : (
                    <ul style={styles.optionsList}>
                        {Object.values(options).map((option, index) => (
                            <li
                                key={option.value}
                                onClick={() => onChange(option)}
                                onMouseEnter={() => setHoveredIndex(index)}
                                onMouseLeave={() => setHoveredIndex(null)}
                                style={{
                                    ...styles.optionItem,
                                    ...(hoveredIndex === index ? styles.optionItemHover : {}),
                                    ...(value === option.value ? styles.optionItemSelected : {})
                                }}
                            >
                                {option.label}
                            </li>
                        ))}
                        {options.length === 0 && searchTerm && (
                            <li style={styles.noResults}>{blocktranslate("No products found")}</li>
                        )}
                    </ul>
                )}
            </div>
        </div>

    );
};

export default SearchableSelect;
